version: '3.9'


services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DEBUG=1
#      - SECRET_KEY=your_secret_key
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASSWORD=Password
      - DB_PORT=5432
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: